### ISSUE TITLE
Adjust checks if detailed XML is not available

### ISSUE THREAD

**Issue by dipsylala** [veracode/scan_health#18]
When performing scan_health on a huge completed scan (70,000 files, 495000 flaws) I got the following warning:

`Warning: There was no detailed report for Build id 41349805. Has the scan finished?`

I suspect this may have been due to a timeout in pulling the detailed XML.

Consequently, it inaccurately reported "No flaws were found in this scan"

Could we:

* Differentiate between a timeout error pulling down the detailed report and the absence of a report?
* For checks that are reliant on the detailed XML report that they could not be run due to the absence of detailed XML.

**Comment by antfie** [comment]
The Veracode API call to <https://analysiscenter.veracode.com/api/5.0/detailedreport.do?build_id=41349805> returned an HTTP status of 200 after 300.81 seconds (5 minutes) with the following body:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<error>No report available.</error>
```

In the case where a build ID is provided instead of a scan URL, it is expected the tool will give up if a detailed report cannot be found. Whilst it may be possible to work around this, using scan URLs is the preferred route, and in that case the tool was able to provide some report output because other details could be extracted from the URL. Passing in a build ID was a convenience feature which works only when a detailed report is available.

It is worth noting that the Detailed Report for this scan in the Veracode Platform did not render, thus there appears to be a Veracode Platform issue with this scan. I recommend raising a support ticket to capture that.
